tweaks from provisioning ubuntu 14.10

diff --git a/dotfiles/profile b/dotfiles/profile
--- a/dotfiles/profile
+++ b/dotfiles/profile
@@ -35,7 +35,7 @@ source_file() {
       then
         printf "$file\n"
       fi
-      . $file
+      . $file || echo "ERROR! There was a problem sourcing '$file'"
     fi
 }
 
